# Generated by Django 4.0.4 on 2022-05-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caste_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caste_category', models.CharField(max_length=255, unique=True, verbose_name='Caste Category')),
            ],
            options={
                'verbose_name': 'Caste Category',
                'verbose_name_plural': 'Caste Category',
                'ordering': ['caste_category'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=255, unique=True, verbose_name='Department ID')),
                ('department_name', models.CharField(max_length=255, verbose_name='Department Name')),
                ('department_code', models.SmallIntegerField(verbose_name='Department Code')),
                ('year_of_establishment', models.SmallIntegerField(verbose_name='Year of Establishment')),
                ('year_of_termination', models.SmallIntegerField(blank=True, null=True, verbose_name='Year of Termination')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['department_id'],
            },
        ),
    ]
