# Generated by Django 4.0.4 on 2022-06-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='full_programme_code',
            field=models.CharField(editable=False, help_text='4-digit Numeric Code uniquely identifying a programme', max_length=4, unique=True, verbose_name='Full Programme Code'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='programme_id',
            field=models.CharField(max_length=255, verbose_name='Programme ID'),
        ),
    ]
