# Generated by Django 4.0.4 on 2022-08-29 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['full_program_code'], 'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
    ]
