# Generated by Django 4.0.4 on 2022-05-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_code',
            field=models.CharField(max_length=2, verbose_name='Department Code'),
        ),
    ]
