# Generated by Django 4.0.4 on 2022-05-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caste_Category',
            fields=[
                ('caste_category', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Caste Category',
                'verbose_name_plural': 'Caste Category',
                'ordering': ['caste_category'],
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('gender', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Gender',
                'verbose_name_plural': 'Gender',
                'ordering': ['gender'],
            },
        ),
    ]
