# Generated by Django 3.2.7 on 2022-05-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caste_category',
            options={'ordering': ['caste_category'], 'verbose_name': 'Caste Category', 'verbose_name_plural': 'Caste Category'},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'ordering': ['gender'], 'verbose_name': 'Gender', 'verbose_name_plural': 'Gender'},
        ),
    ]
