# Generated by Django 3.2.7 on 2022-06-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caste_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caste_category', models.CharField(max_length=255, unique=True, verbose_name='Caste Category')),
            ],
            options={
                'verbose_name': 'Caste Category',
                'verbose_name_plural': 'Caste Categories',
                'ordering': ['caste_category'],
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=255, unique=True, verbose_name='Gender')),
            ],
            options={
                'verbose_name': 'Gender',
                'verbose_name_plural': 'Genders',
                'ordering': ['gender'],
            },
        ),
        migrations.CreateModel(
            name='Marital_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(max_length=255, unique=True, verbose_name='Marital Status')),
            ],
            options={
                'verbose_name': 'Marital Status',
                'verbose_name_plural': 'Marital Status',
                'ordering': ['marital_status'],
            },
        ),
        migrations.CreateModel(
            name='Qualifying_Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifying_exam', models.CharField(max_length=255, unique=True, verbose_name='Qualifying Exam')),
            ],
            options={
                'verbose_name': 'Qualifying Exam',
                'verbose_name_plural': 'Qualifying Exams',
                'ordering': ['qualifying_exam'],
            },
        ),
        migrations.CreateModel(
            name='Work_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(max_length=255, unique=True, verbose_name='Work Type')),
            ],
            options={
                'verbose_name': 'Work Type',
                'verbose_name_plural': 'Work Types',
                'ordering': ['work_type'],
            },
        ),
    ]
