# Generated by Django 4.0.4 on 2022-05-22 18:10

import admission.models.advertisement
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.BigIntegerField(unique=True, verbose_name='Applicant ID')),
                ('type_of_applicant', models.BooleanField(choices=[(True, 'Indian Applicant'), (False, 'Foreign Applicant')], default=True, verbose_name='Type of Applicant')),
                ('nationality', models.CharField(default='India', max_length=255, verbose_name='Nationality')),
                ('marital_status', models.BooleanField(choices=[(True, 'Married'), (False, 'Unmarried')], verbose_name='Marital Status')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('father_or_spouse_name', models.CharField(max_length=255, verbose_name="Father's/Spouse Name")),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=255, verbose_name='Gender')),
                ('contact_number', models.BigIntegerField(verbose_name='Contact Number')),
                ('parent_contact_number', models.BigIntegerField(verbose_name='Parent Contact Number')),
                ('pwd', models.BooleanField(verbose_name='Persons with Disabilities (PwD)')),
                ('disability', models.CharField(max_length=255, null=True, verbose_name='Type of Disability')),
                ('c_address', models.TextField(verbose_name='Address')),
                ('c_city', models.CharField(max_length=255, verbose_name='City')),
                ('c_state', models.CharField(max_length=255, verbose_name='State')),
                ('c_pin', models.IntegerField(verbose_name='Pin/Zip')),
                ('p_address', models.TextField(verbose_name='Address')),
                ('p_city', models.CharField(max_length=255, verbose_name='City')),
                ('p_state', models.CharField(max_length=255, verbose_name='State')),
                ('p_pin', models.IntegerField(verbose_name='Pin/Zip')),
                ('caste_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.caste_category')),
            ],
            options={
                'verbose_name': 'Personal Profile',
                'verbose_name_plural': 'Personal Profile',
                'ordering': ['applicant_id'],
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement_id', models.BigIntegerField(unique=True, verbose_name='Advertisement ID')),
                ('academic_year', models.IntegerField(default=2022, verbose_name='Academic Year')),
                ('programme', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=admission.models.advertisement.upload_file)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.department')),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['advertisement_id'],
            },
        ),
    ]
