# Generated by Django 4.0.4 on 2022-05-21 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('applicant_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Applicant ID')),
                ('type', models.BooleanField(choices=[(True, 'Indian Applicant'), (False, 'Foreign Applicant')], verbose_name='Type')),
                ('marital_status', models.BooleanField(choices=[(True, 'Married'), (False, 'Unmarried')], verbose_name='Marital Status')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('father_or_spouse_name', models.CharField(max_length=255, verbose_name="Father's/Spouse Name")),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('contact_number', models.BigIntegerField(verbose_name='Contact Number')),
                ('parent_contact_number', models.BigIntegerField(verbose_name='Parent Contact Number')),
                ('pwd', models.BooleanField(verbose_name='Persons with Disabilities (PwD)')),
                ('disability', models.CharField(max_length=255, null=True, verbose_name='Type of Disability')),
                ('c_address', models.TextField(verbose_name='Address')),
                ('c_city', models.CharField(max_length=255, verbose_name='City')),
                ('c_state', models.CharField(max_length=255, verbose_name='State')),
                ('c_pin', models.IntegerField(verbose_name='Pin/Zip')),
                ('p_address', models.TextField(verbose_name='Address')),
                ('p_city', models.CharField(max_length=255, verbose_name='City')),
                ('p_state', models.CharField(max_length=255, verbose_name='State')),
                ('p_pin', models.IntegerField(verbose_name='Pin/Zip')),
                ('caste_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constants.caste_category')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constants.gender')),
            ],
            options={
                'verbose_name': 'Personal Profile',
                'verbose_name_plural': 'Personal Profile',
                'ordering': ['applicant_id'],
            },
        ),
    ]
