# Generated by Django 3.2.7 on 2022-05-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('advertisement_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Advertisement ID')),
                ('academic_year', models.IntegerField(default=58)),
                ('department', models.CharField(max_length=255)),
                ('programme', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['advertisement_id'],
            },
        ),
    ]
