# Generated by Django 3.2.7 on 2022-05-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='file',
            field=models.FileField(default=1234, upload_to='files'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='academic_year',
            field=models.IntegerField(default=2022, verbose_name='Academic Year'),
        ),
    ]
