# Generated by Django 4.0.4 on 2022-06-06 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_applied',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Applied on'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='advertisement_id',
            field=models.CharField(editable=False, max_length=10, unique=True, verbose_name='Advertisement ID'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='session',
            field=models.CharField(help_text='2-digit Session Code', max_length=2, verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_id',
            field=models.CharField(editable=False, max_length=17, unique=True, verbose_name='Application ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='disability',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type of Disability'),
        ),
    ]
