# Generated by Django 4.0.4 on 2022-08-29 15:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['application_id'], 'verbose_name': 'Recommendation', 'verbose_name_plural': 'Recommendations'},
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='analytical_ability',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='goal_clarity',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='motivation',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='oral_expression_english',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='overall_intellectual_ability',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='overall_potential',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='referral_id',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='research_potential',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='work_independently',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='work_with_others',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='written_expression_english',
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Referral ID')),
                ('overall_intellectual_ability', models.CharField(choices=[('Uncertain', 'Uncertain'), ('Below 50%', 'Below 50%'), ('Top 50%', 'Top 50%'), ('Top 20%', 'Top 20%'), ('Top 10%', 'Top 10%'), ('Top 5%', 'Top 5%'), ('Top 1%', 'Top 1%')], max_length=255, verbose_name='Overall Intellectual Ability')),
                ('analytical_ability', models.CharField(choices=[('Uncertain', 'Uncertain'), ('Below 50%', 'Below 50%'), ('Top 50%', 'Top 50%'), ('Top 20%', 'Top 20%'), ('Top 10%', 'Top 10%'), ('Top 5%', 'Top 5%'), ('Top 1%', 'Top 1%')], max_length=255, verbose_name='Analytical Ability')),
                ('goal_clarity', models.CharField(choices=[('Uncertain', 'Uncertain'), ('Below 50%', 'Below 50%'), ('Top 50%', 'Top 50%'), ('Top 20%', 'Top 20%'), ('Top 10%', 'Top 10%'), ('Top 5%', 'Top 5%'), ('Top 1%', 'Top 1%')], max_length=255, verbose_name='Clarity of Goal')),
                ('overall_potential', models.CharField(choices=[('Uncertain', 'Uncertain'), ('Below 50%', 'Below 50%'), ('Top 50%', 'Top 50%'), ('Top 20%', 'Top 20%'), ('Top 10%', 'Top 10%'), ('Top 5%', 'Top 5%'), ('Top 1%', 'Top 1%')], max_length=255, verbose_name='Overall Potential')),
                ('oral_expression_english', models.CharField(choices=[('Uncertain', 'Uncertain'), ('Below 50%', 'Below 50%'), ('Top 50%', 'Top 50%'), ('Top 20%', 'Top 20%'), ('Top 10%', 'Top 10%'), ('Top 5%', 'Top 5%'), ('Top 1%', 'Top 1%')], max_length=255, verbose_name='Oral Expression in English')),
                ('written_expression_english', models.CharField(choices=[('Uncertain', 'Uncertain'), ('Below 50%', 'Below 50%'), ('Top 50%', 'Top 50%'), ('Top 20%', 'Top 20%'), ('Top 10%', 'Top 10%'), ('Top 5%', 'Top 5%'), ('Top 1%', 'Top 1%')], max_length=255, verbose_name='written Expression in English')),
                ('work_independently', models.CharField(choices=[('Uncertain', 'Uncertain'), ('Below 50%', 'Below 50%'), ('Top 50%', 'Top 50%'), ('Top 20%', 'Top 20%'), ('Top 10%', 'Top 10%'), ('Top 5%', 'Top 5%'), ('Top 1%', 'Top 1%')], max_length=255, verbose_name='Ability to Work Independently')),
                ('work_with_others', models.CharField(choices=[('Uncertain', 'Uncertain'), ('Below 50%', 'Below 50%'), ('Top 50%', 'Top 50%'), ('Top 20%', 'Top 20%'), ('Top 10%', 'Top 10%'), ('Top 5%', 'Top 5%'), ('Top 1%', 'Top 1%')], max_length=255, verbose_name='Ability to Work with Others')),
                ('research_potential', models.CharField(choices=[('Uncertain', 'Uncertain'), ('Below 50%', 'Below 50%'), ('Top 50%', 'Top 50%'), ('Top 20%', 'Top 20%'), ('Top 10%', 'Top 10%'), ('Top 5%', 'Top 5%'), ('Top 1%', 'Top 1%')], max_length=255, verbose_name='Research Potential')),
                ('motivation', models.CharField(choices=[('Uncertain', 'Uncertain'), ('Below 50%', 'Below 50%'), ('Top 50%', 'Top 50%'), ('Top 20%', 'Top 20%'), ('Top 10%', 'Top 10%'), ('Top 5%', 'Top 5%'), ('Top 1%', 'Top 1%')], max_length=255, verbose_name='Motivation')),
                ('recommendation', models.CharField(choices=[('Uncertain', 'Uncertain'), ('Not Recommended', 'Not Recommended'), ('Unenthusiastically', 'Unenthusiastically'), ('Fairly Strongly', 'Fairly Strongly'), ('Strongly', 'Strongly'), ('Enthusiastically, without reservation', 'Enthusiastically, without reservation')], max_length=255, verbose_name='You Recommend this applicant')),
                ('recommendation_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission.recommendation')),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'ordering': ['recommendation_id'],
            },
        ),
    ]
