# Generated by Django 3.2.7 on 2022-06-01 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='advertisement_number',
            field=models.CharField(default=django.utils.timezone.now, help_text='2-digit Advertisement Number', max_length=2, verbose_name='Advertisement Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='advertisement_id',
            field=models.CharField(editable=False, max_length=6, unique=True, verbose_name='Advertisement ID'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='session',
            field=models.CharField(help_text='2-digit Session code', max_length=2, verbose_name='Session'),
        ),
    ]
