# Generated by Django 4.0.4 on 2022-08-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_alter_education_detail_certificate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education_detail',
            options={'ordering': ['applicant_id'], 'verbose_name': 'Educational Information', 'verbose_name_plural': 'Educational Information'},
        ),
        migrations.AlterField(
            model_name='education_detail',
            name='percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percent or CPI/CGPA'),
        ),
    ]
