# Generated by Django 4.0.4 on 2022-05-22 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_education_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=255, verbose_name='Examination')),
                ('examination', models.CharField(max_length=255, verbose_name='Name of Examination Passed')),
                ('university', models.CharField(max_length=255, verbose_name='Board/ Institute/ University')),
                ('duration', models.IntegerField(verbose_name='Duration of Degree/Diploma in Years')),
                ('status', models.CharField(choices=[('Completed', 'Completed')], max_length=255, verbose_name='Status')),
                ('year_of_passing', models.IntegerField(verbose_name='Expected Year of Passing')),
                ('marks_type', models.CharField(choices=[('Percent of Marks', 'Percent of Marks'), ('CPI/CGPA', 'CPI/CGPA')], max_length=255, verbose_name='Percent of Marks or CPI/CGPA')),
                ('percent', models.IntegerField(verbose_name='Percent or CPI/CGPA')),
                ('out_of', models.IntegerField(verbose_name='Out of CPI/CGPA')),
                ('division', models.CharField(choices=[('First', 'First')], max_length=255, verbose_name='Class/Division')),
                ('specialization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Specialization (if any)')),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.application')),
            ],
            options={
                'verbose_name': 'Educationional Information',
                'verbose_name_plural': 'Educational Information',
                'ordering': ['application_id'],
            },
        ),
        migrations.CreateModel(
            name='Project_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters')], max_length=255, verbose_name='Degree')),
                ('university', models.CharField(max_length=255, verbose_name='Name of University/Institute')),
                ('year_of_submission', models.IntegerField(verbose_name='Year of Submission')),
                ('supervisor', models.CharField(max_length=255, verbose_name='Name of Supervisor')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.application')),
            ],
            options={
                'verbose_name': 'Project Detail',
                'verbose_name_plural': 'Project Details',
                'ordering': ['application_id'],
            },
        ),
        migrations.DeleteModel(
            name='Education_Details',
        ),
    ]
