# Generated by Django 4.0.4 on 2022-05-22 20:45

import admission.models.advertisement
import admission.models.education
import admission.models.examination
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_education_detail_project_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education_detail',
            name='certificate',
            field=models.FileField(default=django.utils.timezone.now, upload_to=admission.models.education.upload_certificate, verbose_name='Certificate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education_detail',
            name='marksheet',
            field=models.FileField(default=django.utils.timezone.now, upload_to=admission.models.education.upload_marksheet, verbose_name='Marksheet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='file',
            field=models.FileField(upload_to=admission.models.advertisement.upload_file, verbose_name='Advertisement File'),
        ),
        migrations.CreateModel(
            name='Qualifying_Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination', models.CharField(choices=[('GATE', 'GATE'), ('CAT', 'CAT'), ('GMAT', 'GMAT'), ('JAM', 'JAM'), ('GRE', 'GRE'), ('DMAT', 'DMAT')], max_length=255, verbose_name='Name of Examination')),
                ('registration_number', models.CharField(max_length=255, verbose_name='Registration Number')),
                ('document', models.FileField(upload_to=admission.models.examination.upload_document, verbose_name='Document')),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.application')),
            ],
            options={
                'verbose_name': 'Project Detail',
                'verbose_name_plural': 'Project Details',
                'ordering': ['application_id'],
            },
        ),
    ]
