# Generated by Django 4.0.4 on 2022-05-22 21:06

import admission.models.recommendation
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_education_detail_certificate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualifying_examination',
            options={'ordering': ['application_id'], 'verbose_name': 'Qualifying Examination', 'verbose_name_plural': 'Qualifying Examinations'},
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_id', models.CharField(max_length=255, unique=True, verbose_name='Referral ID')),
                ('referree_email', models.EmailField(max_length=254, verbose_name='Referree Email')),
                ('letter_of_recommendation', models.FileField(upload_to=admission.models.recommendation.upload_recommendation, verbose_name='Document')),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.application')),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'ordering': ['referral_id'],
            },
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=255, verbose_name='Name of Organization')),
                ('post_held', models.CharField(max_length=255, verbose_name='Post Held')),
                ('work_type', models.CharField(choices=[('Regular', 'Regular'), ('Temporary', 'Temporary'), ('Permanent', 'Permanent'), ('Contract', 'Contract')], max_length=255, verbose_name='Post Held')),
                ('from_date', models.DateField(verbose_name='From')),
                ('to_date', models.DateField(verbose_name='To')),
                ('duration', models.IntegerField(verbose_name='Period of Employment in Months')),
                ('responsibilities', models.CharField(max_length=255, verbose_name='Nature of Responsibilities')),
                ('emoluments', models.CharField(max_length=255, verbose_name='Gross Emoluments')),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.application')),
            ],
            options={
                'verbose_name': 'Employment Detail',
                'verbose_name_plural': 'Employment Details',
                'ordering': ['application_id'],
            },
        ),
    ]
